### ISSUE TITLE
Understanding FRAX Total Supply

### ISSUE THREAD

**Issue by dannywitters** [FraxFinance/frax-solidity#108]
Trying to better understand the total FRAX supply numbers.

![IMAGE 2021-11-18 10:23:11](https://user-images.githubusercontent.com/54670112/142397536-f71c65d8-a892-44f8-847f-871b65805118.jpg)

The totalSupply number on frax.finance shows that of ETH mainnet. Does this supply take into account the canonical native tokens from other chains? 

If my understanding is correct, the totalSupply on ETH mainnet accounts for the bridged, but not the canonical on other chains. So the total FRAX in circulation is actually the sum of canonical values across chains.

Am I missing something here?

**Comment by FortisFortuna** [comment]
The non-mainnet canonical FRAX and FXS are ultimately backed 1-to-1 with bridge tokens
