### ISSUE TITLE
How FPI is peg to CPI data ?

### ISSUE THREAD

**Issue by wenceslas-sanchez** [FraxFinance/frax-solidity#169]
Hi guys,

I am really impressed of the FPI project since it's stablecoin peg to off-chain inflation data, and I would like to have a better understanding on how it works exactly; I mean, how do you force the peg ?

I looked at your code, and the only reference of the [CPITrackerOracle](https://github.com/FraxFinance/frax-solidity/blob/master/src/hardhat/contracts/Oracle/CPITrackerOracle.sol) is in the [FPIControllerPool](https://github.com/FraxFinance/frax-solidity/blob/master/src/hardhat/contracts/FPI/FPIControllerPool.sol#L50). It seems that you compute the absolute relative distance between FPI and CPI values. This distance is then used in [calcMintFPI](https://github.com/FraxFinance/frax-solidity/blob/master/src/hardhat/contracts/FPI/FPIControllerPool.sol#L274) and [calcRedeemFPI](https://github.com/FraxFinance/frax-solidity/blob/master/src/hardhat/contracts/FPI/FPIControllerPool.sol#L311) methods, and it's used to generate an error if the FPI value is out-of-bounds. In my opinion, this is not a peg mecanism since it seems to block both the mint and redeem. 

That's why I wonder where the peg mecanism happens ? Maybe it's in [FPIControllerPool](https://github.com/FraxFinance/frax-solidity/blob/master/src/hardhat/contracts/FPI/FPIControllerPool.sol#L50) and I misunderstood something idk. 

Thank you for those who will take the time to answer me.

... and 🎅🏻 🎄 **Merry Christmas 🎄 🎅🏻 !!**

**Comment by FortisFortuna** [comment]
The protocol is earning minting fees as well as farming income, which helps to maintain the peg. The current FPI target price is the last month price (set at $1 in Dec 2021) multiplied by the official government CPI-U percent difference. It ramps up to this new price over a 30 day period, then refreshes again with new month data.
