### ISSUE TITLE
Unused mapping in `FraxferryV2/FerryOnL1.sol`

### ISSUE THREAD

**Issue by pegahcarter** [FraxFinance/frax-solidity#214]
I found an unused mapping here: 
https://github.com/FraxFinance/frax-solidity/blob/fc9810d72c520d256965b81b6c9cc6aa95d07d9d/src/hardhat/contracts/FraxferryV2/FerryOnL1.sol#L32.  Is this residual code or intended to be used?

**Comment by GauravPatil7050** [comment]
The 'fee_exempt_addrs' mapping allows captains to specify addresses that should not be charged fees when using the ferry service. 

uint fee;
if (fee_exempt_addrs[_captain][msg.sender]) {
    fee = 0;
} else {
    // Fee calculation logic based on captain's fee parameters
}

**Comment by GauravPatil7050** [comment]
Your issue have been solved right?!

**Comment by pegahcarter** [comment]
Yes @GauravPatil7050 .
