### ISSUE TITLE
Why different variants are implemented as separate contracts?

### ISSUE THREAD

**Issue by gisek** [FraxFinance/frax-solidity#33]
Hi Guys

I've been recently going through your code and I found that you create a bunch of almost identical contracts. For example here: https://github.com/FraxFinance/frax-solidity/tree/master/contracts/Oracle/Variants

Actually the implementations of all the contracts in the directory above are exactly the same apart form contract name and corresponding file name.

Coming from non-blockchain background I'm wondering why did you decide to put every pair in a separate contract? Is it for easier deployment?

**Comment by FortisFortuna** [comment]
It makes hardhat testing easier
