### ISSUE TITLE
FraxPool.sol has an extra approve() on redemption functions

### ISSUE THREAD

**Issue by jasonhuan** [FraxFinance/frax-solidity#7]
In FraxPool.sol L242, L274-275, L296, there is an extra approve() which is not necessary for transferring the tokens back to the redeemer in collectRedemption(). This bug has been reported by @samczsun.

Link to bug: https://github.com/FraxFinance/frax-solidity/blob/d1cb9a728c3027828762fbc3f276230e4938f5e0/contracts/Frax/Pools/FraxPool.sol#L242

**Comment by jasonhuan** [comment]
This bug has been fixed in commit: https://github.com/FraxFinance/frax-solidity/commit/c476638458b4ec24b1854fe09db4710a135741e8.

25,000 FXS will be rewarded, subject to bug bounty rules and vesting.

**Comment by ytrezq** [comment]
@corddry hi, I found an infinite inflation bug not on Ethereum but because of an L2 intrestic characteristics. Where should I report it?

**Comment by samkazemian** [comment]
Hey @ytrezq is the bug referring to the same scope and file as fraxpool.sol as before? Or is it a new issue you want to open a new thread on? This issue topic is for a bug back from 2020. 

Regardless, you can reach out to me on Telegram for secure communication using this link https://t.me/samkazemian

You can also reach out to Travis Moore on Telegram as well using this link https://t.me/FortisFortuna_89

**Comment by samkazemian** [comment]
Understood. Can you let me know your Telegram username to communicate privately? My Telegram username is @samkazemian (the same as my github and my Twitter).

**Comment by ytrezq** [comment]
@samkazemian : Ok, I just sent you a message from @ytrezq on Telegram.

**Comment by FortisFortuna** [comment]
Just sent you a message on TG
