### ISSUE TITLE
FXS does not implement optional ERC20 name

### ISSUE THREAD

**Issue by Ivshti** [FraxFinance/frax-solidity#9]
The FXS contract here: https://github.com/FraxFinance/frax-solidity/blob/master/contracts/FXS/FXS.sol

Does not implement the optional ERC20 property `name()`

While it is optional, many applications depend on: just one example is [Uniswap](https://github.com/Uniswap/uniswap-interface/blob/975570fa97eca75eb8f1cddd730d32eeb7a50589/src/hooks/Tokens.ts#L64), and as a consequence the FXS token will not be able to be added as a custom token by Uniswap users.

**Comment by FortisFortuna** [comment]
Ty. Fixed in https://github.com/FraxFinance/frax-solidity/pull/10
