### ISSUE TITLE
Explain the error

### ISSUE THREAD

**Issue by skyhuihui** [FraxFinance/frax-solidity#95]
Frax.sol：
frax_price() instructions X FRAX = 1 USD. in 151 line.
fxs_price()  instructions X FXS = 1 USD. in 156 line.
Should be 1 FRAX = X USD, 1 FXS = X USD.
I am looking for frax and hope to hear back.

**Comment by skyhuihui** [comment]
![image](https://user-images.githubusercontent.com/33145232/132444420-259786ca-6cac-4297-a30e-46442526ea0e.png)
1 fxs = 5.21U

**Comment by FortisFortuna** [comment]
Looks like a typo
